// Generated by gencpp from file yolov7_ros/ObjectTracking2DArray.msg
// DO NOT EDIT!


#ifndef YOLOV7_ROS_MESSAGE_OBJECTTRACKING2DARRAY_H
#define YOLOV7_ROS_MESSAGE_OBJECTTRACKING2DARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace yolov7_ros
{
template <class ContainerAllocator>
struct ObjectTracking2DArray_
{
  typedef ObjectTracking2DArray_<ContainerAllocator> Type;

  ObjectTracking2DArray_()
    {
    }
  ObjectTracking2DArray_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::yolov7_ros::ObjectTracking2DArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yolov7_ros::ObjectTracking2DArray_<ContainerAllocator> const> ConstPtr;

}; // struct ObjectTracking2DArray_

typedef ::yolov7_ros::ObjectTracking2DArray_<std::allocator<void> > ObjectTracking2DArray;

typedef boost::shared_ptr< ::yolov7_ros::ObjectTracking2DArray > ObjectTracking2DArrayPtr;
typedef boost::shared_ptr< ::yolov7_ros::ObjectTracking2DArray const> ObjectTracking2DArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yolov7_ros::ObjectTracking2DArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yolov7_ros::ObjectTracking2DArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace yolov7_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::yolov7_ros::ObjectTracking2DArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yolov7_ros::ObjectTracking2DArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolov7_ros::ObjectTracking2DArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yolov7_ros::ObjectTracking2DArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolov7_ros::ObjectTracking2DArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yolov7_ros::ObjectTracking2DArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yolov7_ros::ObjectTracking2DArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::yolov7_ros::ObjectTracking2DArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::yolov7_ros::ObjectTracking2DArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yolov7_ros/ObjectTracking2DArray";
  }

  static const char* value(const ::yolov7_ros::ObjectTracking2DArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yolov7_ros::ObjectTracking2DArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::yolov7_ros::ObjectTracking2DArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yolov7_ros::ObjectTracking2DArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObjectTracking2DArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yolov7_ros::ObjectTracking2DArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::yolov7_ros::ObjectTracking2DArray_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // YOLOV7_ROS_MESSAGE_OBJECTTRACKING2DARRAY_H
