(cl:defpackage yolov7_ros-msg
  (:use )
  (:export
   "<OBJECTTRACKING2D>"
   "OBJECTTRACKING2D"
   "<OBJECTTRACKING2D>"
   "OBJECTTRACKING2D"
   "<OBJECTTRACKING2DARRAY>"
   "OBJECTTRACKING2DARRAY"
   "<OBJECTTRACKING2DARRAY>"
   "OBJECTTRACKING2DARRAY"
  ))

